server:
  port: 8889

spring:
  datasource:
    username: ****
    password: ****
    url: ****
    driver-class-name: com.mysql.cj.jdbc.Driver
  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


text:
  key: "'private_key'"
  construct: "'construct_key'"
  privateKey: "b7Kt3$2Q4g!@#2-1"